name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: '7.0.203'

    - name: Restore dependencies
      run: dotnet restore src
      
    - name: Build
      run: dotnet build src --no-restore

    - name: Test main project
      run: dotnet test src --no-build --verbosity normal

    - name: Test Parlo.tests project
      run: dotnet test tests/Parlo.Tests/Parlo.Tests.csproj --no-build --verbosity normal
